<?php
/**
 * Template Name: Disclaimer Template
 *
 */
get_header(); ?>
<div class="bg">

<!-- Page Title
		============================================= -->
<section id="page-title">

	<div class="container clearfix">
		<h1>Disclaimer</h1>
		<ol class="breadcrumb">
			<li><a href="<?php bloginfo('url'); ?>/">Home</a></li>
			<li class="active">Disclaimer</li>
		</ol>
	</div>

</section><!-- #page-title end -->

<div class="container ptb-50 white-bg">
	<div class="row">
		<div class="col-sm-12">
			<p class="surgery-title nobottommargin pb-10">Disclaimer</p>
			<p>The information contained in this service is not intended nor implied to be a substitute for professional medical advice. Always seek the advice of your physician or other qualified health provider prior to starting any new treatment or with any questions you may have regarding a medical condition. Nothing contained in the service is intended to be for medical diagnosis or treatment.</p>
			<p>THIS CONTENT IS PROVIDED BY ABRAMS EYECARE ASSOCIATES AS A SERVICE TO ITS CUSTOMERS. THIS WEBSITE DOES NOT CONTAIN INFORMATION ABOUT ALL DISEASES, NOR DOES THIS WEBSITE CONTAIN ALL MEDICAL INFORMATION THAT MAY BE RELEVANT. ALL CONTENT PROVIDED IN THIS WEBSITE IS ONLY GENERAL HEALTH INFORMATION AND IS ONLY INTENDED TO FACILITATE COMMUNICATION BETWEEN YOU AND YOUR HEALTHCARE PROVIDER. IT IS NOT INTENDED FOR DIAGNOSIS AND CANNOT PROVIDE A DIAGNOSIS FOR ANY PARTICULAR INDIVIDUAL AND SHOULD NOT BE USED AS A SUBSTITUTE FOR SEEKING PROFESSIONAL MEDICAL ADVICE, DIAGNOSIS, TREATMENT, OR CARE. ALL SPECIFIC MEDICAL QUESTIONS YOU HAVE ABOUT YOUR MEDICAL CONDITION, TREATMENT, CARE, OR DIAGNOSIS SHOULD BE PRESENTED TO YOUR OWN PROFESSIONAL HEALTHCARE PROVIDER.</p>
			<p>EXCEPT AS EXPRESSLY AND UNAMBIGUOUSLY STATED OTHERWISE, ABRAMS EYECARE ASSOCIATES DOES NOT ENDORSE, OPERATE, CONTROL, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT, BRAND, METHOD, TREATMENT, INFORMATION, OR SERVICES ON THE WEBSITE, IN ANY WAY.</p>
			<p>THE INFORMATION, SERVICES, AND PRODUCTS CONTAINED IN THIS WEB SITE ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED.</p>
			<p>TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, ABRAMS EYECARE ASSOCIATES AND ITS MEDICAL ADVISORS, CONSULTANTS, AND STAFF (COLLECTIVELY "ABRAMS EYECARE ASSOCIATES") DISCLAIM AND EXCLUDE ALL WARRANTIES WITH RESPECT TO ALL INFORMATION, SERVICES, AND PRODUCTS CONTAINED IN THIS WEBSITE, EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
			<p>ABRAMS EYECARE ASSOCIATES DOES NOT WARRANT THAT INFORMATION, SERVICES, AND PRODUCTS CONTAINED IN THIS WEBSITE WILL SATISFY YOUR REQUIREMENTS OR THAT IT IS WITHOUT DEFECT OR ERROR.</p>
			<p class="surgery-title nobottommargin pb-10">Limitation on Liability</p>
			<p>AS PARTIAL CONSIDERATION FOR YOUR USE OF AND ACCESS TO THIS WEB SITE, YOU AGREE THAT: (I) IN NO EVENT WILL ABRAMS EYECARE ASSOCIATES OR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THIS WEBSITE OR ANY SITE LINKED TO THIS WEBSITE, BE LIABLE TO YOU IN ANY MANNER WHATSOEVER FOR ANY DECISION MADE OR ACTION OR NON-ACTION TAKEN BY YOU IN RELIANCE UPON THE INFORMATION PROVIDED THROUGH THIS WEBSITE; AND (II) THE AGGREGATE LIABILITY OF ABRAMS EYECARE ASSOCIATES, OR ANY OF ITS DISTRIBUTORS OR DEALERS, ARISING FROM OR RELATING TO THIS AGREEMENT (REGARDLESS OF THE FORM OF ACTION OR CLAIM, E.G. CONTRACT, WARRANTY, TORT, STRICT LIABILITY, NEGLIGENCE, MALPRACTICE, FRAUD, AND/OR OTHERWISE) IS LIMITED TO THE PURCHASE PRICE OF ANY PRODUCTS YOUR PURCHASED FROM ABRAMS EYECARE ASSOCIATES IN THE RELEVANT TRANSACTION; AND (III) ABRAMS EYECARE ASSOCIATES SHALL NOT IN ANY CASE BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, EVEN IF ABRAMS EYECARE ASSOCIATES HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. </p>
			<p class="surgery-title nobottommargin pb-10">Product Claims</p>
			<p>All claims regarding Abrams EyeCare Associates formulations contained within this site, and the efficacy of ingredients, have not been evaluated by the Food and Drug Administration. Abrams EyeCare Associates formulations are not intended to diagnose, treat, cure or prevent any disease.</p>
			<p>Abrams EyeCare Associates assumes no responsibility for claims regarding the efficacy, warranty, or safety of any product or service offered by a Abrams EyeCare Associates Network affiliate. For more information regarding Abrams EyeCare Associates' Affiliate Network products or services, please contact that company directly.</p>
		</div>
	</div>
</div>

<?php get_footer(); ?>